[package]
name = "thumbelina"
version = "0.1.0"
authors = ["Haile Lagi"]
edition = "2018"

[lib]
name = "thumbelina"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.24.0"
image = "0.24.2"
